name: Deploy Code

on:
  push:
    branches:
      - Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip code
        run: |
          zip -r deployment.zip . -x ".git/*" ".github/*"

      - name: Deploy to endpoint
        run: |
          curl -X POST \
            -F "file=@deployment.zip" \
            ps://qeswu1v32f.execute-api.ap-southeast-2.amazonaws.com/pipeline/deploy/uat
