name: Deploy Code

on:
  push:

jobs:

  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT
          
  main-job:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Read Index file content
        id: read_index
        run: |
          INDEX_CONTENT=$(cat index.mjs)
          echo "index_content<<EOF" >> $GITHUB_OUTPUT
          echo "$INDEX_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Read Readme file content
        id: read_readme
        run: |
          README_CONTENT=$(cat README.md)
          echo "readme_content<<EOF" >> $GITHUB_OUTPUT
          echo "$README_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send File contents to endpoint as JSON
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"indexContent\": \"${{ steps.read_index.outputs.index_content }}\", \"readmeContent\": \"${{ steps.read_readme.outputs.readme_content }}\"}" \
            https://qeswu1v32f.execute-api.ap-southeast-2.amazonaws.com/pipeline/deploy/prod

  dev-job:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Read Index file content
        id: read_index
        run: |
          INDEX_CONTENT=$(cat index.mjs)
          echo "index_content<<EOF" >> $GITHUB_OUTPUT
          echo "$INDEX_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Read Readme file content
        id: read_readme
        run: |
          README_CONTENT=$(cat index.mjs)
          echo "readme_content<<EOF" >> $GITHUB_OUTPUT
          echo "$README_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send File contents as base64 encoded zip file to endpoint as JSON    
      # - name: Zip code
        run: |
          zip -r deployment.zip . -x ".git/*" ".github/*" . base64 deployment.zip > deployment.b64
      - name: Deploy to endpoint
        run: |
          curl -X POST \
            -H "Content-Type: application/octet-stream" \
            --data-binary "@deployment.b64" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Branch: ${{ github.ref_name }}" \
            -H "Repository: ${{ github.repository }}" \
            https://jsf58ekjw3.execute-api.us-west-2.amazonaws.com/prod/deploy
          if [ $? -ne 0 ]; then
            echo "Deployment failed!"
            exit 1
          fi

  common-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run common script
        run: echo "Running common job, triggered by ${{ github.ref_name }}"